postgres:
  target: default
  outputs:
    default:
      type: postgres
      host: localhost
      user: root
      password: password
      database: postgres
      schema: public
      port: 5432
